AWSTemplateFormatVersion: "2010-09-09"

Description:
  This stack is made to build an infrastructure for a wordpress page. 

Parameters:
  VPCTemplateURL:
    Type: String
    Description: Provide de vpc template url for stack. 

  RDSTemplateURL:
    Type: String
    Description: Provide the rds template url for stack.
  
  EC2TemplateURL:
    Type: String
    Description: Provide the EC2 template url for stack.

  Environment:
    Type: String
    Description: Name to use for the tags at all resources that will be created in this section.
  
  VpcCidr:
    Type: String
    Description: CIDR block (IP Mask) for the resource. 
  
  PublicSubnet1CIDR:
    Type: String
    Description: CIDR for public subnet 1.
  
  PublicSubnet2CIDR:
    Type: String
    Description: CIDR for public subnet 2.

  PrivateSubnet1CIDR:
    Type: String
    Description: CIDR for private subnet 1.

  PrivateSubnet2CIDR:
    Type: String
    Description: CIDR for private subnet 2.
  
  DBName:
    Type: String
    Description: Database name for mysql instance.
  
  DBUserName:
    Type: String
    Description: Master username.
  
  DBPassword: 
    Type: String
    Description: Master password.
    NoEcho: True

  InstanceType:
    Type: String
    Description: EC2 instance type to place the wordpress server.

  ImageId:
    Type: String
    Description: Place here the id of an AMI instance.


Resources:

  # VPC Template
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref VPCTemplateURL
      Parameters: 
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  # RDS
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref RDSTemplateURL
      Parameters: 
        Environment: !Ref Environment
        DBName: !Ref DBName
        SecurityGroupCIDR: !Ref VpcCidr
        VPC: !GetAtt VPC.Outputs.VPC
        PrivateSubnet1: !GetAtt VPC.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPC.Outputs.PrivateSubnet2
        DBUserName: !Ref DBUserName
        DBPassword: !Ref DBPassword
  
  # EC2
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref EC2TemplateURL
      Parameters: 
        Environment: !Ref Environment
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        VPC: !GetAtt VPC.Outputs.VPC